### ISSUE TITLE
Install couchbase-lite 1.2.1 using cocoapods or carthage

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#1171]
Is there any way to install version 1.2.1 using either couchbase or carthage? Tried both, but hoping there is something I missed.

**Comment by chakrit** [comment]
Can we have this? I believe this should be a simple fix.

```
*** Skipped building couchbase-lite-ios due to the error:
Dependency "couchbase-lite-ios" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/couchbase/couchbase-lite-ios/issues/new
```

**Comment by pasin** [comment]
Thanks for reporting this. We haven't officially release 1.2.1 yet, and we will look into this.

**Comment by whitespace-software** [comment]
It was working well using 1.2.1 but today it fails:

*** Fetching couchbase-lite-ios
*** Checking out couchbase-lite-ios at "790bc33cc43ad3debab433fe5ddd75cffff8c3da"
A shell task failed with exit code 1:
fatal: Unable to look up github.com (port 9418) (nodename nor servname provided, or not known)
Clone of 'git://github.com/snej/sqlite3-unicodesn.git' into submodule path 'vendor/sqlite3-unicodesn' failed

**Comment by snej** [comment]
Well, look at the error:

>fatal: Unable to look up github.com (port 9418)

Github was down briefly yesterday. Try it again now.

**Comment by marcuzb** [comment]
Thanks for coming back, I'm working at Whitespace Software.  We've had quite a few goes at this today, and I'm wondering if just one was a coincidence when Github was down.

We just tried again... using a Cartfile of 

`github "couchbase/couchbase-lite-ios" "release/1.2.1"`

This is what was working well for us, but now ends with the following from Carthage...

> The following build commands failed:
	PhaseScriptExecution Build\ Fat\ Library /Users/marcusbroome/Library/Developer/Xcode/DerivedData/CouchbaseLite-gskplxqeckftrtgpeteouyttsmud/Build/Intermediates/CouchbaseLite.build/Release-iphoneos/CBL\ SQLite\ Storage.build/Script-27E66ACB1A7305B10091DA3F.sh
(1 failure)

And using the following Cartfile  (as updated in the README)

`github "couchbase/couchbase-lite-ios" "release/1.2.0"`

we get:

>*** Fetching couchbase-lite-ios
*** Checking out couchbase-lite-ios at "7f33ceb50bf78af5d7491d2571764598dca17b67"
*** xcodebuild output can be found in /var/folders/6r/n8n0vxp90kn0r_j592rmq9_40000gn/T/carthage-xcodebuild.WWdMWy.log
*** Skipped building couchbase-lite-ios due to the error:
Dependency "couchbase-lite-ios" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/couchbase/couchbase-lite-ios/issues/new

**Comment by zgramana** [comment]
We pushed some build fixes yesterday, and it looks like we need to update the Cartfile.

**Comment by snej** [comment]
The Cartfile isn't something we maintain, it's a file created by a project that wants to import us.
I'm running the carthage tool now with a Cartfile of `github "couchbase/couchbase-lite-ios" "release/1.2.1"` and I'll look into what's going wrong.

**Comment by snej** [comment]
Yup, it failed the same way. Found the actual error:

>Taking device build from: /Couchbase/Carthage/Carthage/Checkouts/couchbase-lite-ios/build/CouchbaseLite/Build/Products/Release-appletvos  
>Taking simulator build from: /Couchbase/Carthage/Carthage/Checkouts/couchbase-lite-ios/build/CouchbaseLite/Build/Products/Release-appletvsimulator  
>...I will output a universal build to: /Couchbase/Carthage/Carthage/Checkouts/couchbase-lite-ios/build/CouchbaseLite/Build/Products/Release-tvOS-universal  
>lipo: for current configuration (Release) creating output file: /Couchbase/Carthage/Carthage/Checkouts/couchbase-lite-ios/build/CouchbaseLite/Build/Products/Release-tvOS-universal/libCBLSQLiteStorage.a  
>fatal error: lipo: /Couchbase/Carthage/Carthage/Checkouts/couchbase-lite-ios/build/CouchbaseLite/Build/Products/Release-appletvos/libCBLSQLiteStorage.a and /Couchbase/Carthage/Carthage/Checkouts/couchbase-lite-ios/build/CouchbaseLite/Build/Products/Release-appletvsimulator/libCBLSQLiteStorage.a have the same architectures (x86_64) and can't be in the same fat output file

I think this is a problem with the build fix I checked in yesterday, but I don't understand why it's only showing up in this context, not during our builds.

**Comment by snej** [comment]
I fixed the previously-fixed fix again :-p
Carthage now builds the release/1.2.1 branch … at least for iOS and tvOS. For Mac, it seems to find the "CBL Mac+SQLCipher" scheme first and builds that, but it fails due to lack of a SQLCipher binary. I don't know how to control which scheme Carthage builds if there's more than one for a platform.

**Comment by snej** [comment]
I just filed https://github.com/Carthage/Carthage/issues/1209 regarding the problems with building for Mac.

**Comment by marcuzb** [comment]
Thanks - back up and running with 1.2.1 & Carthage.  Much appreciated.

**Comment by skela** [comment]
Yup, works for me too, excellent.

Still doesn't work for cocoapods though, so I'll leave this issue open :)

**Comment by snej** [comment]
Looking through this I can't find any description of what specifically fails when building CocoaPods. I'm going to close this bug, since 99% of the discussion was about Carthage and that's fixed; feel free to file a new issue regarding current CocoaPods problems. Thanks.
