### ISSUE TITLE
SQLite database file corruption

### ISSUE THREAD

**Issue by brendand** [couchbase/couchbase-lite-ios#1424]
I'm getting some complaints from customers that their SQLite database files are becoming corrupted somehow. It sometimes manifests itself with missing views or errors about map blocks. 

I'm pretty sure I'm being very careful to access the database on the main thread in most places unless I'm doing some sort of batch operation in which case I call backgroundTellDatabaseName and create a new document and CBLModel object from a passed in document ID within the block. 

Here's an example screenshot showing one issue. Notice the duplicate `rowid` value? And the null key and null sequence values.

<img width="888" alt="screen shot 2016-08-30 at 3 09 35 pm" src="https://cloud.githubusercontent.com/assets/586075/18107283/9105dff0-6ec4-11e6-954d-b37a56e6ef4d.png">

What could be causing this and how do I prevent it from happening?

I do have `autosave` on my `CBLModel` subclass turned on, so maybe that's causing an issue since I do explicit saves in a bunch of places too. I've turned that feature off for my next update, just in case it's causing some conflict. Or maybe it's being caused by the database access on the sync thread?

The above screenshot came from a database who's log journal mode was "WAL". 

The end result of things like this are that the data doesn't show in the app.

Any help or things I should be looking out for would be very welcome.

--------
* Version:   1.3 GM
* Client OS: OS X 10.11
* Server:    n/a

**Comment by pasin** [comment]
I'm not sure how the NULL key can happen. According to the [code](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_SQLiteViewStorage.m#L576-L579), the null key should be ignored.

Duplicated rows seem to be a threading issue. You may check if the app can query the same view created by the same database object on 2 different threads.

> I do have autosave on my CBLModel subclass turned on, so maybe that's causing an issue since I do explicit saves in a bunch of places too.

I have found [this comment](https://github.com/couchbase/couchbase-lite-ios/blob/1679c4436699aa837509c5706ca49a05e744cd04/Source/CBL_SQLiteViewStorage.m#L574-L577) in the code. @snej has this been fixed?

**Comment by brendand** [comment]
It often just manifests itself with a "malformed disk image" error too.

I do have a central manager class (a subclass of NSDocument & UIDocument) where I create some views that are used to fetch and cache a bunch of CBLModel objects that I use throughout the app. Whenever a sync happens I flush and reload those model objects, but again, on the main thread.

Normally if I try to access a CBLModel object from a different thread that it was created on I get an assertion error and the app crashes. So that I believe is a corruption preventative measure in place by CBL. So maybe there is something with the delayed autosave that's causing the issue.

Or maybe I am using the same view on a non-main thread somewhere.  I know you can't use the same CBLModel objects across threads, but does the same go for the views that are used to fetch the documents in order to create the CBLModel objects?

**Comment by pasin** [comment]
> but does the same go for the views that are used to fetch the documents in order to create the CBLModel objects?

You cannot share the view across the thread as view is also attached to a database object. Every time that you query the view, the index will be updated either before or after depending on `indexUpdateMode` set to the query (by default is before).

**Comment by brendand** [comment]
Ok. Understood. Does the `THREAD-SAFETY VIOLATION` alert on `FMDatabase.m` occur even if you try to access a view on a different thread than it was created on? If that were the case, then no corruption could take place because the assertion would crash the app before it could attempt to access the database on a different thread. From looking at the code it would seem like it should. And if this were the case, then no corruption would ever take place due to this safety measure. Perhaps I'm misunderstanding how it works.

**Comment by pasin** [comment]
I just read the code as well, and it seems like it should do the assertion unless the dispatch queue is used (skip cross-thread validation).

**Comment by pasin** [comment]
I will try to run some code to verify the THREAD-SAFETY VIOLATION and probably try to corrupt the map table, but I couldn't do it until early next week.

**Comment by brendand** [comment]
I wonder if it has something to do with how SQLCipher is compiled? I'm using the Couchbase compiled version of SQLCipher. It's compiled in multithreaded mode, but it almost sounds like the default serialized mode would be better.

From the SQLite docs:

> SQLite supports three different threading modes:
> 
> **Single-thread**. In this mode, all muteness are disabled and SQLite is unsafe to use in more than a single thread at once
> 
> **Multi-thread**. In this mode, SQLite can be safely used by multiple threads provided that no single database connection is used simultaneously in two or more threads.
> 
> **Serialized**. In serialized mode, SQLite can be safely used by multiple threads with no restriction.
> 
> Compile-time selection of threading mode
> 
> Use the SQLITE_THREADSAFE compile-time parameter to selected the threading mode. If no SQLITE_THREADSAFE compile-time parameter is present, then serialized mode is used. This can be made explicit with -DSQLITE_THREADSAFE=1. With -DSQLITE_THREADSAFE=0 the threading mode is single-thread. With -DSQLITE_THREADSAFE=2 the threading mode is multi-thread.
> .

The Couchbase compiled SQLCipher is compiled with the setting `-DSQLITE_THREADSAFE=2` which is the Multi-thread mode. Which means that no single database connection can be used simultaneously in two or more threads.

Although I suspect that each CBLManager instance creates a separate connection to the database. I currently have just a main thread CBLManager and a read-only background CBLManager on its own dispatch_queue (for my Apple Watch version of my app). Plus there's the separate thread that the CBLReplicator process runs on.

During replication I post notifications on the main thread which cause the UI to be refreshed, possibly multiple times during replication, especially when there's lots of data to replicate.

Just today a customer of mine said that they were missing a bunch of data in their database. It turns out that it was one of their views which was generating a `database disk image is malformed` error. But they could get a filtered set of data because the filter system in my app generates a separate map table for every different filter. It was the unfiltered list of records that was returning nothing because that particular view was damaged.

**Comment by brendand** [comment]
I'm going to re-compile it with -DSQLITE_THREADSAFE=1 just to be on the safe side and see how that goes.

**Comment by brendand** [comment]
Regarding this issue, a customer of mine just emailed me and told me they had a power failure. When they restarted my app, they got the following error:

malformed database schema (maps_8_sequence) - index maps_8_sequence already exists.

They've had to restore from a Time Machine backup.

**Comment by pasin** [comment]
From https://www.sqlite.org/howtocorrupt.html, SQLite claims to be resistant to the database corruption but not immune. 

Note that we complied SQLCipher with -DSQLITE_POWERSAFE_OVERWRITE=1 and -DSQLITE_ENABLE_LOCKING_STYLE=1, and use the default FULL [synchronize](https://www.sqlite.org/pragma.html#pragma_synchronous) mode. I understand that all of these setup should help SQLite to survive from corruption during the power loss but maybe not true.

@brendand beside the power loss event, are there any other cases that your customers has encountered the database corruption issue?

**Comment by snej** [comment]
@brendand please DO NOT change the threading mode from Multithreaded. This is the desired mode, and I have no idea what subtle changes/problems could occur with Serialized. (If nothing else, it's likely to be significantly slower.)

**Comment by snej** [comment]
The duplicate `rowid`s in the table shown in the screenshot are bad news — `rowid` is the internal column used as the primary key (it's not part of the schema we define), so it should by definition be unique. My guess is that SQLite's internal b-tree is damaged.

This could be the result of running a query on the same database instance from multiple threads. The indexing code runs inside a database transaction to prevent any other connections from making changes, but a call to the same instance would bypass that protection because it ends up calling the same DB handle.

The threading check in CBL_FMDatabase isn't bulletproof, especially if the caller is using dispatch queues. It's only meant as a last-ditch way of possibly detecting the problem. If you're not getting those assertion failures, it does _not_ prove that your threading is correct.

**No Couchbase Lite Obj-C class or method is thread-safe, except for a couple of "do-this-later" methods that are explicitly called out as such.** The docs are pretty clear on this:

>In Objective-C, a Manager instance and the object graph associated with it may only be accessed from the thread or dispatch queue that created the Manager instance.

This is standard behavior for Cocoa APIs. Nearly everything from the collection classes to CoreData to UIKit has the same limitations. There are good reasons for this: making everything thread-safe at every level introduces major performance overhead, and it's also nearly impossible to get completely correct.

**Comment by snej** [comment]
More on the threading check: I've just refreshed my memory of the code. The check is **disabled** if the Manager is bound to a dispatch queue instead of a thread. The reason is:
```obj-c
        // This check doesn't work if the current queue is separate from dispatchQueue but has
        // dispatchQueue as its target queue. This is a legal setup but will trigger the
        // exception. There's no way to detect this using the public API (I believe) so I have to
        // just skip the check entirely when using dispatch queues.
```
I had to do this, because with the check enabled there were legal situations that caused false positives, i.e. assertion failures / crashes.

**Comment by brendand** [comment]
@snej Well it's too late as I've already published an update with the changed threading mode. I haven't noticed any speed issues with doing that.

> Serialized. In serialized mode, SQLite can be safely used by multiple threads with no restriction.

It would seem that it should be even safer to use this mode than Multithreaded mode.

@pasin Some have said that they experienced a crash in the app and when they opened it up again the database file was corrupted. But I only just published the new update with Serialized threading set today so I'll see if there are any problems going forward.

**Comment by snej** [comment]
>It would seem that it should be even safer to use this mode than Multithreaded mode.

The most it can do is prevent internal corruption inside SQLite. But if such a situation occurs — multiple threads calling the same CBL storage object — then lots of other bad things are still possible since those objects have no thread-safety. So you could easily crash, or get bogus results, or mess up the database at a higher level (i.e. violating CBL invariants that are not enforced as SQL constraints.)

**Comment by brendand** [comment]
@snej I only have 2 managers. The main one I use is created on the main thread (Mac and iOS):

```
	if (!_couchManager) {
		CBLManagerOptions options = {.readOnly = false};
		weakSelf.couchManager = [[CBLManager alloc] initWithDirectory: url.path
															  options: &options
																error: &error];
        }
```

And the other one is only ever created on iOS when the watch app is accessed. I've never had this SQLite file corruption on the iOS version so far. Only the Mac version seems to suffer from the corruption problem. It doesn't even create the background manager.

The background manager is created like this (only on the iOS version):

```
	__weak TFDatabaseDocument *weakSelf = self;
	dispatch_sync(self.couchbase_queue, ^{
			CBLManagerOptions options = {.readOnly = true};
			NSError *error = nil;
			weakSelf.backgroundCouchManager = [[CBLManager alloc] initWithDirectory: url.path
																			options: &options
																			  error: &error];
			
			weakSelf.backgroundCouchManager.dispatchQueue = self.couchbase_queue;			
			[weakSelf openBackgroundDatabase];		
	});

```

**Comment by brendand** [comment]
> So you could easily crash, or get bogus results, or mess up the database at a higher level (i.e. violating CBL invariants that are not enforced as SQL constraints.)

Well now I'm scared.

The only time I do background database operations is by using CBL's backgroundTellDatabaseNamed function, like this:

```
[self.databaseDocument.couchManager backgroundTellDatabaseNamed:self.databaseDocument.documentID to:^(CBLDatabase * _Nonnull database) {
		
		CBLDocument *doc = [database documentWithID:formID];
		TFForm *blockForm = [TFForm modelForDocument:doc];
		blockForm.documentDefaults = weakSelf.databaseDocument.documentDefaults;
....
  }
```

And you can see that I load in a local copy of the object using the provided database instance. I do that everywhere in my app. Other queries and updates occur on the main thread. These are just the ones where I need some sort of progress indicator to be shown or on longer running operations.

**Comment by snej** [comment]
>Well now I'm scared.

Concurrent programming is hard :( It scares me too. There are a few mechanisms that make it safer, which are just starting to go mainstream in new languages like Rust and Pony; they work by making it literally impossible for threads to share mutable data. (As in, if the program could violate this, it won't even compile!) There are indications that Swift may go this way in the future, but probably not for another year or two.

Hm … the block running in the background calls `weakSelf.databaseDocument`. Is that a CBL object? Or is it an accessor method that might call into CBL objects belonging to the main thread?

A safer way to write this code would be to call `weakSelf.databaseDocument.documentDefaults` outside the block and assign it to a variable, and then use that variable in the block. That way you avoid multi-threaded calls into `self`.

**Comment by brendand** [comment]
`weakSelf.databaseDocument` is my NSDocument subclass which is where I store the instance of my `CBLManager` class.

The `documentDefaults` property is just my own homegrown NSUserDefaults system that stores defaults in a .plist file within the NSDocument's package bundle instead of using the regular NSUserDefaults. So there's no database access going on with that thing.

I do have code on my `TFForm` class which fetches an array of `TFField` objects (as well as other model objects). But since I'm using  the provided `database` property of the `backgroundTellDatabaseNamed` method to create a new local version of my `TFForm` object, I thought that should be fine. The `fields` method on my `TFForm` class will use the `TFForm's` database object to do the fetching of the `TFField` objects using a CBLQuery object.

So technically a copy of the same objects will be in the main thread and in this background thread created by CBL. But I don't think they would ever reference each other or get mixed up. So I think I'm safe with that. Hopefully anyway.

**Comment by brendand** [comment]
> A safer way to write this code would be to call weakSelf.databaseDocument.documentDefaults outside the block and assign it to a variable, and then use that variable in the block. That way you avoid multi-threaded calls into self.

Thanks for the tip. A lot of my code references weakSelf within blocks:

For example:

```

[blockForm findAndReplace:weakSelf.searchTerm
					   formSearch:blockSearch
					  searchField:blockSearchField
						replaceType:weakSelf.replaceType
						withValue:weakSelf.replaceValue
						 withType:weakSelf.replaceWithType
					 replaceField:blockReplaceField
					 matchingType:weakSelf.matchType
						  recordIDs:selectedRecordIds
						 progress:progress
				 databaseDocument:weakSelf.databaseDocument
						 database:database];

dispatch_async(dispatch_get_main_queue(), ^{
	[weakSelf.window endSheet:weakSelf.progressPanel.window];
	[weakSelf.window.sheetParent endSheet:weakSelf.window];
			
	[[NSNotificationCenter defaultCenter] postNotificationName:kTFFieldUpdatedNotification object:weakSelf.databaseDocument.mainWindowController];
			
	});
```

Could referencing weakSelf be a source of the problems I'm having?

**Comment by snej** [comment]
I've updated the `vendor/fmdb` submodule to be more rigorous about checking for re-entrant calls. Could you try updating that submodule to its master (commit b859ca3)? It will now produce an assertion failure any time there's an attempt to use the same SQLite handle on multiple threads at once.

**Comment by snej** [comment]
>Could referencing weakSelf be a source of the problems I'm having?

It's not necessarily a problem. It depends on how thread-safe your own code is, and whether the code that's called ends up calling into Couchbase Lite. For example the code in your last comment looks fine, because the block runs on the main thread and is accessing AppKit objects that naturally should be used on the main thread. But you do have to carefully check everything that you call from such a block.

**Comment by brendand** [comment]
Excellent. I'll give the update a go.

**Comment by pasin** [comment]
I'm closing this ticket now. @brendand if you have any updates or think that there is an issue in CBL , we can reopen this issue. Thanks!

**Comment by brendand** [comment]
@pasin Unfortunately this is still a constant source of trouble for my app. Nearly every day I am helping someone out with a corrupted database. I've combed through my code to make sure I'm accessing my database objects on the main thread. I have code with breakpoints set to make sure that if I call a query off the main thread that it stops the app.

I do use the `backgroundTellDatabaseNamed:` method to do some batch processing such as exporting or importing records. But I make sure that I pass in the documentID of my CBLDocument and then fetch it again within the block as a new instance and then do whatever processing I do on it. 

I never had this problem before with the previous version of my app where I used `FMDB` directly myself. I think it was because I always used the `FMDatabaseQueue` class for all of my fetching, so there was no chance of any simultaneous access to the underlying SQLite file from different threads. 

It's very frustrating and could be the end of my product if I can't figure out where I'm going wrong that's causing this issue.

I contacted Couchbase today to see if there was a chance I could hire someone there to do a code review with me, but they said I needed a subscription to the Enterprise distribution. I don't use the server version nor do I use Sync Gateway. I just use CBL for iOS and Mac.

I'm happy to pay for someone's time to look at my code with me and help me to spot any issues that could be causing this SQLite database file corruption.

**Comment by pasin** [comment]
Is this the same issue as https://github.com/couchbase/couchbase-lite-ios/issues/1482 or different?

**Comment by pasin** [comment]
I'm happy to help looking at your code. Maybe you can send me (pasin@couchbase.com) only the parts of the codes that you are not sure if you are doing the right thing.

If you would like to make some experiments, I would suggest to build and use a SQLite/SQLCipher binary with the serialized mode enabled. If the problem still exists, it probably means that the root cause is not related to threading. 

On a side note, from https://github.com/couchbase/couchbase-lite-android/issues/985, it seems like the database corruption issue was solved after enabling the serialized mode. We couldn't find in CBL Android code where could cause the database corruption as CBL-Android doesn't share database connection between threads but somehow the serialized mode did help.

**Comment by brendand** [comment]
No this is different than #1482. Although #1482 is still a problem, this issue apparently just seems to happen randomly. A customer may be using his database fine one moment, they quit the app and when they launch it again and open their database, they get the `malformed disk image` error or various other errors about not being able to read the map tables. Sometimes the FTS search index is corrupted, sometimes it's a map table sometimes it's the revs table that's corrupt. 

I can send you my main NSDocument subclass which contains the main code where I create and open the database. Perhaps there's something there that you can spot. But I have no idea if that's where the problem lies. It could be or it might not be.

As for the Serialized mode, I had compiled it with that mode and released an update with it like that at one point. But in my most recent update I turned it off again and kept the defaults that you had setup because of Jens warning that I shouldn't change it from Multithreading mode.

I'll try serialized mode again.

I wonder if it would be beneficial for CBL to use FMDB's FMDatabaseQueue to manage database access instead of whatever you're doing now? That would guarantee serialized access to the database. I used to use that in the older version of my app and didn't have these kinds of problems.

I did find some code today where I was referencing a CBLAttachment on my CBLModel subclass from a thread that was different than the main thread. It was used for generating thumbnails in the background. Not sure if that could have caused the corruption, but I've reworked it now to pass only the CBLAttachment's content NSData to the image resizing code instead of the CBLAttachment itself.

**Comment by guidedways** [comment]
@brendand did Serialized mode help you eventually?

**Comment by brendand** [comment]
Well I reworked all my code to ensure I was doing everything in a thread-safe way and not passing around CBLModel objects between threads. I'm using `SQLITE_THREADSAFE=2` which is `Multi-Threaded`, the default configuration for the CBL integration of SQLCipher.

**Comment by guidedways** [comment]
Thanks, I suspect it was the mmap issue in my case as we already use SQLite in a thread safe way and since corruption isn't happening on iOS with the same code, I am hopeful disabling mmap explicitly will sort it out.
