### ISSUE TITLE
Carthage build fails on XCode 8

### ISSUE THREAD

**Issue by noradaiko** [couchbase/couchbase-lite-ios#1487]
Hi,

I couldn't install the library with Carthage.
Error message:

```
Check dependencies
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "*****" with a private key was found.
warning: no rule to process version file '/Users/nora/Library/Developer/Xcode/DerivedData/CouchbaseLite-fonunnsqpnqzshbfayirborqmizy/Build/Intermediates/CouchbaseLite.build/Debu
g-iphoneos/CBL iOS framework.build/DerivedSources' for architecture armv7
warning: no rule to process version file '/Users/nora/Library/Developer/Xcode/DerivedData/CouchbaseLite-fonunnsqpnqzshbfayirborqmizy/Build/Intermediates/CouchbaseLite.build/Debu
g-iphoneos/CBL iOS framework.build/DerivedSources' for architecture arm64
```

Valid code signing identities are specified in my project settings but it seems to be ignored.
Any suggestion will be appreciated!

---
- Version:   1.3.2

**Comment by noradaiko** [comment]
any updates?

**Comment by pasin** [comment]
The Carthage now works with the Master branch. I fixed one issue that the `SwiftForest` scheme cannot be built. Thanks.

**Comment by pasin** [comment]
@noradaiko 1.3.2 branch is obsolete now. We plan to release 1.4.0 instead. Meanwhile please use the master branch with the Carthage.

**Comment by noradaiko** [comment]
thanks!

**Comment by zygoat** [comment]
Carthage still does not build the 1.4.0 branch with Xcode 8. It still has the `SecRandomCopyBytes` problem described in #1460.
