### ISSUE TITLE
Replication stops after hitting 400 Invalid attachment error 

### ISSUE THREAD

**Issue by ajithrnayak** [couchbase/couchbase-lite-ios#864]
Integrated Couchbase-lite 1.1.1 enterprise edition from [Index of /couchbase-lite-ios/release/1.1.1/ios/1.1.1-5][1]. And, pull replication with CouchDB stops after replication error hits **400 Invalid attachment**. 

Earlier versions of CBL were logging a warning as 
`‖ WARNING: Oops, server is trying to send a compressed attachment, I can't do that yet
18:31:25.548‖ WARNING: CBLMultipartDocumentReader[_id="_design/app"]: received unparseable MIME multipart response: Stopped`

>[_id="_design/app"]
>[_id="_design/Admin"]

Looking at the document IDs, these are _design documents with attachments that are not needed for Mobile device; only Web platform uses it. So, is there a way to skip _design documents from replication? Or, may be, skip document replication by default when invalid attachment is found?

[1]: http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.1.1/ios/1.1.1-5/

**Comment by snej** [comment]
Could you show the metadata ("_"-prefixed properties) of the design doc that causes the error?

You can use a pull replication filter to skip design docs. The filter needs to be installed on the remote server (CouchDB), then you set its name as the `filter` property of the CBLReplication.

**Comment by ajithrnayak** [comment]
Here's the doc - https://friendpaste.com/4gpK3xqGU811nQDfW4Sptf (err.. they have JS files in them). 



And, I'll use filter to skip design docs; thank you.

**Comment by ajithrnayak** [comment]
>‖ WARNING: CBL_Puller[http://someServer/database_one] failed to write {E9D77E4D-FB3B-4BF9-AF42-6E7AF57CDF2F #2-d588bf31a35a77ff43c7afe7be460e97}: status=491
SYNCMGR: active=0; status=2; 0/0; 400 Invalid attachment
‖ WARNING: CBL_Puller[http://someServer/database_two] failed to write {53740b12-b4d2-4a29-884d-afd9c60c3a61 #2-6e2b187e68125b88d877cac10ca63ed4}: status=491
SYNCMGR: active=0; status=2; 0/0; 400 Invalid attachment

I used filter to skip design documents. Now, there are no warnings on versions older than 1.1.1, replication works smoothly. 

However, CBL 1.1.1 still stops replication with same **400 Invalid attachment** error; with a different documents(not design docs) this time. The documents have following meta data-
[E9D77E4D-FB3B-4BF9-AF42-6E7AF57CDF2F][1]
[53740b12-b4d2-4a29-884d-afd9c60c3a61][2]


[1]:https://friendpaste.com/4gpK3xqGU811nQDfW4Shwe
[2]:https://friendpaste.com/4gpK3xqGU811nQDfW4b9ek

**Comment by pasin** [comment]
@ajithrnayak,
The 400 Invalid attachment issue (not the design doc one) that you have just encountered should be fixed in the next build of 1.1.1 binary. I will post the link once we have the binary ready.

**Comment by ajithrnayak** [comment]
@pasin  , thank you. Yeah! I made a build myself from commit [5b858e3][1] and I couldn't see 400 invalid attachment issue, nor any warnings.

[1]:https://github.com/couchbase/couchbase-lite-ios/commit/5b858e3b62048f976efcc52afaf1e04b917ce19d

**Comment by pasin** [comment]
Thanks for letting us know. Also the new 1.1.1 build is ready if you are interested in.

http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.1.1/ios/1.1.1-6

**Comment by ajithrnayak** [comment]
@pasin I'm still seeing this issue. Scenario goes like:
- App goes to background
- Device goes to sleep
- make 2 changes and '-save' on other device (**note:** making 1 change works just fine)
- Wake device and bring app to foreground
- replication.lastError throws **`400 Invalid attachment`**

After this pull doesn't works for subsequent changes and push works fine.

_attachment looks like this 
>"64863b_1418896327507.png": {
           "content_type": "image/png",
           "revpos": 2,
           "digest": "md5-g2zwRcmJFPoBlJIYJykSDg==",
           "length": 111221,
           "stub": true
       }

**Comment by pasin** [comment]
@ajithrnayak could you please post the complete JSON document?

I'm opening the issue so that this will not get missed in the next sprint.

**Comment by ajithrnayak** [comment]
@pasin Here it is https://friendpaste.com/7fuz9RELwNfqImn2ZaJ028

**Comment by pasin** [comment]
The document itself looks fine to me. Was the document deleted before the app went to background?

**Comment by pasin** [comment]
Also are there any warning messages shown on the log? They might give us some clues.

**Comment by ajithrnayak** [comment]
This is the log on launching app. I checked documents and they look fine (same as above).
>SYNCMGR: active=0; status=1; 0/0; (null)
SYNCMGR: active=0; status=1; 0/0; (null)
SYNCMGR: active=0; status=1; 0/0; (null)
SYNCMGR: active=1; status=3; 0/0; (null)
WARNING: CBL_Puller[http://server/database] failed to write {E00E42B72CEB48A3862380B45F5A79C7 #5-72798a76630ae392395eec265fed2e57}: status=491
SYNCMGR: active=1; status=3; 0/0; (null)
SYNCMGR: active=1; status=3; 0/0; (null)
SYNCMGR: active=0; status=2; 0/0; (null)
SYNCMGR: active=1; status=3; 4/10; (null)
SYNCMGR: active=1; status=3; 4/24; (null)
SYNCMGR: active=1; status=3; 0/1; (null)
SYNCMGR: active=0; status=2; 0/0; 400 Invalid attachment
WARNING: CBL_Puller[http://server/database] failed to write {EB6ADBDFEE3E49989A8682BF2C63A9B5 #12-51de459f827b83b9503eebc09e9867e0}: status=491
SYNCMGR: active=0; status=2; 0/0; 400 Invalid attachment

**Comment by ajithrnayak** [comment]
>Was the document deleted before the app went to background?
No, it was not deleted.

**Comment by pasin** [comment]
I couldn't reproduce the issue with the same revision and attachment structure as you have posted (If I understand correctly that is the document from the Sync-Gateway).

To be sure that I really have the same structure, I would need to see the JSON document that has the issue on both sides ([1] the device that tried to pull the document side and [2] the sync-gateway side). Could you help me on this?

**Comment by ajithrnayak** [comment]
@pasin No, replication happens with CouchDB. 

Here's the device side document -  https://friendpaste.com/BmMcxVtbgZnRmlkKI2dXs

**Comment by pasin** [comment]
Look like digests are different (SHA1 and MD5). Not sue if we have the code to handle this case. Will need to look into the detail.

**Comment by ajithrnayak** [comment]
Is different digest a problem? It doesn't fails always; all the other documents (those that sync without a problem) also have different digest.

**Comment by pasin** [comment]
Just checked the code and there is no digest check for this case (stub = true).

I'm confused with the revision id. On device, it has `4-4ca58886845ee968e5be0dba27ff645c` and on couch db, it has `3-d80d38b0124a826e1cd3e7b5456473b8`. You explained earlier that you updated the document on another device twice times and tried to sync the document back to the original device. Hence at least on the original device, the generation number (the prefix number at the beginning of the rev id) should be less than the one of the CouchDB. Do I misunderstand anything here? Is it possible we are looking at the wrong document?

**Comment by ajithrnayak** [comment]
Ah! I apologies. Just reproduced issue and here's the document:

rev-1 on CouchDB: https://friendpaste.com/BmMcxVtbgZnRmlkKIjU2B
rev-1 on Device : https://friendpaste.com/BmMcxVtbgZnRmlkKISDdz
and after 2 changes,
rev-3 on CouchDB : https://friendpaste.com/7fuz9RELwNfqImn2Zahrog 

And, why would I get "400 Invalid attachment" error?

**Comment by ajithrnayak** [comment]
@pasin & @snej We are up for a release, but held by this issue. I'm trying to provide more info on this. 

Enabled logging for above mentioned scenario and logs(after app is launched again) are here https://friendpaste.com/2BayCv2bZVFNu4XO2qsUUB

You could notice sync hitting error and stopping replication logs from **line number 784 to 793**. I've quoted the same below.

>‖ SyncVerbose: CBL_Puller[http://local_server/nl_wolterendros_denhaag_04140045_sdk_escamp] inserting 5D7471DD62E942B0AD3E48B7A6EF1BDC ["3-b02f72304d8ba69762882bb47707f81a", "2-bcda3a41d759213e72be4df2a627a44e", "1-0c14bc709abdcc1a22d34b61e29213cb"]
‖ WARNING: CBL_Puller[http://local_server/nl_wolterendros_denhaag_04140045_sdk_escamp] failed to write {5D7471DD62E942B0AD3E48B7A6EF1BDC #3-b02f72304d8ba69762882bb47707f81a}: status=491
‖ Sync: CBL_Puller[http://local_server/nl_wolterendros_denhaag_04140045_sdk_escamp] Progress: set error = 400 Invalid attachment
‖ Sync: CBL_Puller[http://local_server/nl_wolterendros_denhaag_04140045_sdk_escamp] STOPPING...
‖ Sync: Stopping 0 remote requests
‖ SyncVerbose: CBL_Puller[http://local_server/nl_wolterendros_denhaag_04140045_sdk_escamp] finished inserting 1 revisions
‖ Sync: CBL_Puller[http://local_server/nl_wolterendros_denhaag_04140045_sdk_escamp] inserted 1 revs in 0.002 sec (572.7/sec)
‖ Sync: CBL_Puller[http://local_server/nl_wolterendros_denhaag_04140045_sdk_escamp] Progress: set active = 0
‖ SyncVerbose: CBL_Puller[http://local_server/nl_wolterendros_denhaag_04140045_sdk_escamp]: postProgressChanged (0/1, active=0 (batch=0, net=0), online=1)
‖ Sync: CBL_Puller[http://local_server/nl_wolterendros_denhaag_04140045_sdk_escamp] STOPPED

**Comment by pasin** [comment]
I haven't had a chance to test it with CouchDB yet. I will try to reproduce the issue with CouchDB today. Will let you know.

**Comment by pasin** [comment]
Yes, I could reproduce the issue with CouchDB.

Local:
```
{
    "_attachments" =     {
        myattachment =         {
            "content_type" = "text/plain; charset=utf-8";
            digest = "sha1-oaDsDkUDon9gAShhMF9l7cxugW8=";
            length = 51200;
            revpos = 1;
            stub = 1;
        };
    };
    "_id" = doc;
    "_rev" = "1-119725eeb7585545cc849fda550d09b8";
    foo = bar;
}
```

CouchDB:
```
{
   "_id": "doc",
   "_rev": "3-9088185d9a975e429e1366bf1463e4d7",
   "foo": "bar3",
   "_attachments": {
       "myattachment": {
           "content_type": "text/plain; charset=utf-8",
           "revpos": 1,
           "digest": "md5-W3qvModIgI6HVCj3N0O4IQ==",
           "length": 51200,
           "stub": true
       }
   }
}
```

Local Pull replication (GET db/doc?rev....) response:
```
{
  "_id": "doc",
  "_rev": "3-9088185d9a975e429e1366bf1463e4d7",
  "foo": "bar3",
  "_revisions": {
    "start": 3,
    "ids": [
      "9088185d9a975e429e1366bf1463e4d7",
      "3a7f046e6be0574876548e780b032ccf",
      "119725eeb7585545cc849fda550d09b8"
    ]
  },
  "_attachments": {
    "myattachment": {
      "content_type": "text/plain; charset=utf-8",
      "revpos": 1,
      "digest": "md5-W3qvModIgI6HVCj3N0O4IQ==",
      "length": 51200,
      "stub": true,
      "encoding": "gzip",
      "encoded_length": 85
    }
  }
}
```

```

**Comment by pasin** [comment]
This issue has already been fixed in the master branch but the fixes didn't get included in v1.1.1.

Issues https://github.com/couchbase/couchbase-lite-ios/issues/802, https://github.com/couchbase/couchbase-lite-ios/issues/843

Fixes https://github.com/couchbase/couchbase-lite-ios/commit/a20e014d9c4b4feabc65a66430793a1661c21c2f, https://github.com/couchbase/couchbase-lite-ios/commit/aefde4addfdad0f110d10fdc62f8840406883cfd

**Comment by ajithrnayak** [comment]
Alright, glad to hear that. Thank you, @pasin. I can make a build myself from master. But, is this going to be included in v.1.1.1 anytime soon?

**Comment by ajithrnayak** [comment]
I see https://github.com/couchbase/couchbase-lite-ios/commit/a20e014d9c4b4feabc65a66430793a1661c21c2f (i,e #802) already on [v.1.1.1 list of fixes][1]. 

[1]:https://github.com/couchbase/couchbase-lite-ios/issues?q=milestone:1.1.1+is:closed

**Comment by pasin** [comment]
The fix list is compiled from the issues that are tagged with 1.1.1. It was supposed to go in to v1.1.1 based on the tag but we missed that commits when cherry-picking the fixes. I'm checking now if it's still possible to go into 1.1.1 or it's too late.

**Comment by ajithrnayak** [comment]
I couldn't reproduce this on a build from master branch. Cheers!

**Comment by pasin** [comment]
We have just included those fixes in 1.1.1 release. You can download the latest build from [here](http://latestbuilds.hq.couchbase.com/couchbase-lite-ios/release/1.1.1/ios/1.1.1-17/). You may want to try it out.

In the current master branch, we have changed the database file directory layout. It will automatically upgrade from the old structure to the new structure. However 1.1.1 version will not be able to recognize that new structure. This means that switching back from master to 1.1.1 binary may require you to delete your development app first so the 1.1.1 database can be regenerated.
